from __future__ import annotations

from .models import ProviderCapabilities, ProviderProfile, ProviderType, ProtocolMode
from .providers import DEFAULT_CCSWITCH_URL


CATALOG_FIELDS = (
    "display_name",
    "preset_id",
    "description",
    "key_url",
    "docs_url",
    "supports_api_key",
)


def builtin_providers() -> dict[str, ProviderProfile]:
    chat_capabilities = ProviderCapabilities(
        supports_responses=False,
        supports_chat_completions=True,
        supports_usage=True,
        supports_model_listing=True,
    )
    return {
        "ccswitch": ProviderProfile(
            id="ccswitch",
            preset_id="ccswitch",
            display_name="CC Switch",
            description="使用本机路由，由 CC Switch 管理上游密钥与故障转移。",
            docs_url="https://github.com/farion1231/cc-switch",
            provider_type=ProviderType.CCSWITCH,
            protocol_mode=ProtocolMode.AUTO,
            base_url=DEFAULT_CCSWITCH_URL,
            default_model="gpt-5.6-sol",
            reasoning_effort="ultra",
            timeout_seconds=120,
            local_only=True,
            supports_api_key=False,
            is_active=True,
            capabilities=ProviderCapabilities(supports_model_listing=True),
        ),
        "deepseek": ProviderProfile(
            id="deepseek",
            preset_id="deepseek",
            display_name="DeepSeek",
            description="官方 API，适合通用对话和推理模型。",
            key_url="https://platform.deepseek.com/api_keys",
            docs_url="https://api-docs.deepseek.com/",
            provider_type=ProviderType.COMPATIBLE,
            protocol_mode=ProtocolMode.CHAT_COMPLETIONS,
            base_url="https://api.deepseek.com",
            api_key_reference="DEEPSEEK_API_KEY",
            requires_api_key=True,
            default_model="deepseek-v4-flash",
            available_models=["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"],
            capabilities=chat_capabilities,
        ),
        "zhipu": ProviderProfile(
            id="zhipu",
            preset_id="zhipu",
            display_name="智谱 GLM",
            description="智谱官方开放平台，使用 OpenAI 兼容接口。",
            key_url="https://bigmodel.cn/usercenter/proj-mgmt/apikeys",
            docs_url="https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
            provider_type=ProviderType.COMPATIBLE,
            protocol_mode=ProtocolMode.CHAT_COMPLETIONS,
            base_url="https://open.bigmodel.cn/api/paas/v4",
            api_key_reference="ZHIPU_API_KEY",
            requires_api_key=True,
            default_model="glm-5.2",
            available_models=["glm-5.2", "glm-5.1", "glm-5", "glm-4.7", "glm-4.7-flash"],
            capabilities=chat_capabilities,
        ),
        "kimi": ProviderProfile(
            id="kimi",
            preset_id="kimi",
            display_name="Kimi",
            description="月之暗面官方 API，支持长上下文与推理模型。",
            key_url="https://platform.kimi.com/console/api-keys",
            docs_url="https://platform.moonshot.cn/docs/api/chat",
            provider_type=ProviderType.COMPATIBLE,
            protocol_mode=ProtocolMode.CHAT_COMPLETIONS,
            base_url="https://api.moonshot.cn/v1",
            api_key_reference="MOONSHOT_API_KEY",
            requires_api_key=True,
            default_model="kimi-k3",
            available_models=["kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5"],
            capabilities=chat_capabilities,
        ),
        "siliconflow": ProviderProfile(
            id="siliconflow",
            preset_id="siliconflow",
            display_name="硅基流动",
            description="一个密钥访问多家开源模型，连接后读取账号可用列表。",
            key_url="https://cloud.siliconflow.cn/account/ak",
            docs_url="https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions",
            provider_type=ProviderType.COMPATIBLE,
            protocol_mode=ProtocolMode.CHAT_COMPLETIONS,
            base_url="https://api.siliconflow.cn/v1",
            api_key_reference="SILICONFLOW_API_KEY",
            requires_api_key=True,
            default_model="",
            available_models=[],
            capabilities=chat_capabilities,
        ),
        "openai": ProviderProfile(
            id="openai",
            preset_id="openai",
            display_name="OpenAI",
            description="OpenAI 官方 API，支持 Responses 和 Chat Completions。",
            key_url="https://platform.openai.com/api-keys",
            docs_url="https://platform.openai.com/docs/api-reference",
            provider_type=ProviderType.OPENAI,
            protocol_mode=ProtocolMode.AUTO,
            base_url="https://api.openai.com/v1",
            api_key_reference="COUNCIL_OPENAI_API_KEY",
            requires_api_key=True,
            default_model="gpt-4.1-mini",
            available_models=["gpt-4.1-mini", "gpt-4.1", "gpt-4o-mini"],
            capabilities=ProviderCapabilities(
                supports_responses=True,
                supports_chat_completions=True,
                supports_usage=True,
                supports_model_listing=True,
            ),
        ),
        "custom": ProviderProfile(
            id="custom",
            preset_id="custom",
            display_name="自定义兼容接口",
            description="用于 OpenAI-compatible 中转站或自托管服务。",
            provider_type=ProviderType.COMPATIBLE,
            protocol_mode=ProtocolMode.AUTO,
            base_url="http://127.0.0.1:8080/v1",
            api_key_reference="COUNCIL_CUSTOM_API_KEY",
            default_model="",
            available_models=[],
            capabilities=chat_capabilities,
        ),
        "mock": ProviderProfile(
            id="mock",
            preset_id="mock",
            display_name="本地演示",
            description="不联网、不产生费用，用于体验界面和流程。",
            provider_type=ProviderType.MOCK,
            protocol_mode=ProtocolMode.AUTO,
            base_url="",
            default_model="council-mock",
            available_models=["council-mock"],
            local_only=True,
            supports_api_key=False,
            capabilities=ProviderCapabilities(
                supports_responses=False,
                supports_chat_completions=True,
                supports_structured_output=True,
                supports_usage=True,
                supports_model_listing=True,
            ),
        ),
    }


BUILTIN_PROVIDER_IDS = frozenset(builtin_providers())
